export const elementsArray = [
  {
    name: "hydrogen",
    atomicNum: 1,
    symbol: "H",
    category: "Others",
  },

  {
    name: "helium",
    atomicNum: 2,
    symbol: "He",
    category: "Noble gases",
  },
  {
    name: "lithium",
    atomicNum: 3,
    symbol: "Li",
    category: "Alkali metals",
  },
  {
    name: "beryllium",
    atomicNum: 4,
    symbol: "Be",
    category: "Alkaline earth metals",
  },
  {
    name: "boron",
    atomicNum: 5,
    symbol: "B",
    category: "Metalloids",
  },
  {
    name: "carbon",
    atomicNum: 6,
    symbol: "C",
    category: "Others",
  },
  {
    name: "nitrogen",
    atomicNum: 7,
    symbol: "N",
    category: "Others",
  },
  {
    name: "oxygen",
    atomicNum: 8,
    symbol: "O",
    category: "Others",
  },
  {
    name: "fluorine",
    atomicNum: 9,
    symbol: "F",
    category: "Halogens",
  },
  {
    name: "neon",
    atomicNum: 10,
    symbol: "Ne",
    category: "Noble gases",
  },
  {
    name: "sodium",
    atomicNum: 11,
    symbol: "Na",
    category: "Alkali metals",
  },
  {
    name: "magnesium",
    atomicNum: 12,
    symbol: "Mg",
    category: "Alkaline earth metals",
  },
  {
    name: "aluminum",
    atomicNum: 13,
    symbol: "Al",
    category: "Others",
  },
  {
    name: "silicon",
    atomicNum: 14,
    symbol: "Si",
    category: "Metalloids",
  },
  {
    name: "phosphorus",
    atomicNum: 15,
    symbol: "P",
    category: "Others",
  },
  {
    name: "sulfur",
    atomicNum: 16,
    symbol: "S",
    category: "Others",
  },
  {
    name: "chlorine",
    atomicNum: 17,
    symbol: "Cl",
    category: "Halogens",
  },
  {
    name: "argon",
    atomicNum: 18,
    symbol: "Ar",
    category: "Noble gases",
  },
  {
    name: "potassium",
    atomicNum: 19,
    symbol: "K",
    category: "Alkali metals",
  },
  {
    name: "calcium",
    atomicNum: 20,
    symbol: "Ca",
    category: "Alkaline earth metals",
  },
  {
    name: "scandium",
    atomicNum: 21,
    symbol: "Sc",
    category: "Transition metals",
  },
  {
    name: "titanium",
    atomicNum: 22,
    symbol: "Ti",
    category: "Transition metals",
  },

  {
    name: "vandium",
    atomicNum: 23,
    symbol: "V",
    category: "Transition metals",
  },
  {
    name: "chromium",
    atomicNum: 24,
    symbol: "Cr",
    category: "Transition metals",
  },
  {
    name: "manganese",
    atomicNum: 25,
    symbol: "Mn",
    category: "Transition metals",
  },
  {
    name: "iron",
    atomicNum: 26,
    symbol: "Fe",
    category: "Transition metals",
  },
  {
    name: "cobalt",
    atomicNum: 27,
    symbol: "Co",
    category: "Transition metals",
  },
  {
    name: "nickel",
    atomicNum: 28,
    symbol: "Ni",
    category: "Transition metals",
  },
  {
    name: "copper",
    atomicNum: 29,
    symbol: "Cu",
    category: "Transition metals",
  },
  {
    name: "zinc",
    atomicNum: 30,
    symbol: "Zn",
    category: "Transition metals",
  },
  {
    name: "Gallium",
    atomicNum: 31,
    symbol: "Ga",
    category: "Others",
  },
  {
    name: "germanium",
    atomicNum: 32,
    symbol: "Ge",
    category: "Metalloids",
  },
  {
    name: "arsenic",
    atomicNum: 33,
    symbol: "As",
    category: "Metalloids",
  },
  {
    name: "selenium",
    atomicNum: 34,
    symbol: "Se",
    category: "Others",
  },
  {
    name: "bromine",
    atomicNum: 35,
    symbol: "Br",
    category: "Halogens",
  },
  {
    name: "krypton",
    atomicNum: 36,
    symbol: "Kr",
    category: "Noble gases",
  },
  {
    name: "rubidium",
    atomicNum: 37,
    symbol: "Rb",
    category: "Alkali metals",
  },
  {
    name: "strontium",
    atomicNum: 38,
    symbol: "Sr",
    category: "Alkaline earth metals",
  },
  {
    name: "yitrium",
    atomicNum: 39,
    symbol: "Y",
    category: "Transition metals",
  },
  {
    name: "zirconium",
    atomicNum: 40,
    symbol: "Zr",
    category: "Transition metals",
  },
  {
    name: "niobium",
    atomicNum: 41,
    symbol: "Nb",
    category: "Transition metals",
  },
  {
    name: "molybdenum",
    atomicNum: 42,
    symbol: "Mo",
    category: "Transition metals",
  },
  {
    name: "technetium",
    atomicNum: 43,
    symbol: "Tc",
    category: "Transition metals",
  },
  {
    name: "ruthenium",
    atomicNum: 44,
    symbol: "Ru",
    category: "Transition metals",
  },

  {
    name: "rhodium",
    atomicNum: 45,
    symbol: "Rh",
    category: "Transition metals",
  },
  {
    name: "palladium",
    atomicNum: 46,
    symbol: "Pd",
    category: "Transition metals",
  },
  {
    name: "silver",
    atomicNum: 47,
    symbol: "Ag",
    category: "Transition metals",
  },
  {
    name: "cadmium",
    atomicNum: 48,
    symbol: "Cd",
    category: "Transition metals",
  },
  {
    name: "indium",
    atomicNum: 49,
    symbol: "In",
    category: "Others",
  },
  {
    name: "tin",
    atomicNum: 50,
    symbol: "Sn",
    category: "Others",
  },
  {
    name: "antimony",
    atomicNum: 51,
    symbol: "Sb",
    category: "Metalloids",
  },
  {
    name: "tellurium",
    atomicNum: 52,
    symbol: "Te",
    category: "Metalloids",
  },
  {
    name: "iodine",
    atomicNum: 53,
    symbol: "I",
    category: "Halogens",
  },
  {
    name: "xenon",
    atomicNum: 54,
    symbol: "Xe",
    category: "Noble gases",
  },
  {
    name: "cesium",
    atomicNum: 55,
    symbol: "Cs",
    category: "Alkali metals",
  },
  {
    name: "barium",
    atomicNum: 56,
    symbol: "Ba",
    category: "Alkaline earth metals",
  },
  {
    name: "lanthanum",
    atomicNum: 57,
    symbol: "La",
    category: "Transition metals",
  },
  {
    name: "cerium",
    atomicNum: 58,
    symbol: "Ce",
    category: "Lanthanides",
  },
  {
    name: "praseodymium",
    atomicNum: 59,
    symbol: "Pr",
    category: "Lanthanides",
  },
  {
    name: "neodymium",
    atomicNum: 60,
    symbol: "Nd",
    category: "Lanthanides",
  },
  {
    name: "promethium",
    atomicNum: 61,
    symbol: "Pm",
    category: "Lanthanides",
  },
  {
    name: "samarium",
    atomicNum: 62,
    symbol: "Sm",
    category: "Lanthanides",
  },
  {
    name: "europium",
    atomicNum: 63,
    symbol: "Eu",
    category: "Lanthanides",
  },
  {
    name: "gadolinium",
    atomicNum: 64,
    symbol: "Gd",
    category: "Lanthanides",
  },
  {
    name: "terbium",
    atomicNum: 65,
    symbol: "Tb",
    category: "Lanthanides",
  },
  {
    name: "dysprosium",
    atomicNum: 66,
    symbol: "Dy",
    category: "Lanthanides",
  },
  {
    name: "holmium",
    atomicNum: 67,
    symbol: "Ho",
    category: "Lanthanides",
  },
  {
    name: "erbium",
    atomicNum: 68,
    symbol: "Er",
    category: "Lanthanides",
  },
  {
    name: "thulium",
    atomicNum: 69,
    symbol: "Tm",
    category: "Lanthanides",
  },
  {
    name: "ytterbium",
    atomicNum: 70,
    symbol: "Yb",
    category: "Lanthanides",
  },
  {
    name: "lutetium",
    atomicNum: 71,
    symbol: "Lu",
    category: "Lanthanides",
  },
  {
    name: "hafnium",
    atomicNum: 72,
    symbol: "Hf",
    category: "Transition metals",
  },
  {
    name: "tantalium",
    atomicNum: 73,
    symbol: "Ta",
    category: "Transition metals",
  },
  {
    name: "tungsten",
    atomicNum: 74,
    symbol: "W",
    category: "Transition metals",
  },
  {
    name: "rhenium",
    atomicNum: 75,
    symbol: "Re",
    category: "Transition metals",
  },
  {
    name: "osmium",
    atomicNum: 76,
    symbol: "Os",
    category: "Transition metals",
  },
  {
    name: "iridium",
    atomicNum: 77,
    symbol: "Ir",
    category: "Transition metals",
  },
  {
    name: "platinum",
    atomicNum: 78,
    symbol: "Pt",
    category: "Transition metals",
  },
  {
    name: "gold",
    atomicNum: 79,
    symbol: "Au",
    category: "Transition metals",
  },
  {
    name: "mercury",
    atomicNum: 80,
    symbol: "Hg",
    category: "Transition metals",
  },
  {
    name: "thalium",
    atomicNum: 81,
    symbol: "Tl",
    category: "Others",
  },
  {
    name: "lead",
    atomicNum: 82,
    symbol: "Pb",
    category: "Others",
  },
  {
    name: "bismuth",
    atomicNum: 83,
    symbol: "Bi",
    category: "Others",
  },
  {
    name: "polonium",
    atomicNum: 84,
    symbol: "Po",
    category: "Metalloids",
  },
  {
    name: "astatine",
    atomicNum: 85,
    symbol: "At",
    category: "Halogens",
  },
  {
    name: "radon",
    atomicNum: 86,
    symbol: "Rn",
    category: "Noble gases",
  },
  {
    name: "francium",
    atomicNum: 87,
    symbol: "Fr",
    category: "Alkali metals",
  },
  {
    name: "radium",
    atomicNum: 88,
    symbol: "Ra",
    category: "Alkaline earth metals",
  },
  {
    name: "actinium",
    atomicNum: 89,
    symbol: "Ac",
    category: "Actinides",
  },
  {
    name: "thorium",
    atomicNum: 90,
    symbol: "Th",
    category: "Actinides",
  },
  {
    name: "protactinium",
    atomicNum: 91,
    symbol: "Pa",
    category: "Actinides",
  },
  {
    name: "uranium",
    atomicNum: 92,
    symbol: "U",
    category: "Actinides",
  },
  {
    name: "Neptunium",
    atomicNum: 93,
    symbol: "Np",
    category: "Actinides",
  },
  {
    name: "Plutonium",
    atomicNum: 94,
    symbol: "Pu",
    category: "Actinides",
  },
  {
    name: "Americium",
    atomicNum: 95,
    symbol: "U",
    category: "Actinides",
  },
  {
    name: "uranium",
    atomicNum: 92,
    symbol: "U",
    category: "Actinides",
  },
  {
    name: "uranium",
    atomicNum: 92,
    symbol: "U",
    category: "Actinides",
  },
  {
    name: "uranium",
    atomicNum: 92,
    symbol: "U",
    category: "Actinides",
  },
];
